import { Box, Container, Flex, HStack, Icon, Stack, Text } from '@chakra-ui/react';
import { FiArrowLeft } from 'react-icons/fi';
import { ink, inkSoft, cream, line, serif } from '../../theme/brand';

interface PrivacyPolicyPageProps {
  onBack: () => void;
}

const Section = ({ title, children }: { title: string; children: React.ReactNode }) => (
  <Stack spacing={2}>
    <Text fontFamily={serif} fontWeight="700" fontSize="lg" color={ink}>
      {title}
    </Text>
    <Stack spacing={2} color={inkSoft} fontSize="sm" lineHeight="1.8">
      {children}
    </Stack>
  </Stack>
);

const PrivacyPolicyPage = ({ onBack }: PrivacyPolicyPageProps) => (
  <Box bg={cream} minH="100dvh">
    <Flex
      as="header"
      align="center"
      px={{ base: 4, md: 8 }}
      py={4}
      borderBottom="1px solid"
      borderColor={line}
      position="sticky"
      top={0}
      bg="rgba(251,243,233,0.92)"
      backdropFilter="blur(12px)"
      zIndex={10}
    >
      <HStack as="button" onClick={onBack} spacing={2} color={inkSoft} _hover={{ color: ink }}>
        <Icon as={FiArrowLeft} boxSize={4} />
        <Text fontSize="sm" fontWeight="600">
          Back
        </Text>
      </HStack>
    </Flex>

    <Container maxW="720px" py={{ base: 10, md: 16 }} px={{ base: 5, md: 8 }}>
      <Stack spacing={8}>
        <Stack spacing={2}>
          <Text fontFamily={serif} fontWeight="700" fontSize={{ base: '2xl', md: '3xl' }} color={ink}>
            Privacy Policy
          </Text>
          <Text fontSize="sm" color={inkSoft}>
            Last updated: July 2026
          </Text>
        </Stack>

        <Text color={inkSoft} fontSize="sm" lineHeight="1.8">
          Vibeon Learn is a language-learning app. This page explains, plainly, what information we
          collect, why, and how it's handled. We don't sell personal data, and we don't run
          advertising trackers.
        </Text>

        <Section title="What we collect">
          <Text>
            <Text as="span" fontWeight="600" color={ink}>
              Account information:
            </Text>{' '}
            your email address, username, and password (stored as a salted hash, never in plain
            text), plus anything optional you add — first/last name, preferred language, the
            language you're learning, proficiency level, and a daily goal.
          </Text>
          <Text>
            <Text as="span" fontWeight="600" color={ink}>
              Learning activity:
            </Text>{' '}
            your vocabulary progress, quiz and roleplay history, reading and listening session
            results, and streaks/achievements — this is what powers your progress tracking and
            spaced-repetition scheduling.
          </Text>
          <Text>
            <Text as="span" fontWeight="600" color={ink}>
              Voice input:
            </Text>{' '}
            when you use a mic feature (pronunciation practice, dictation, voice messages), your
            speech is processed to produce a text transcription and a score. The audio itself is
            not saved as a file — only the resulting text and accuracy result are stored against
            your account.
          </Text>
        </Section>

        <Section title="How we use it">
          <Text>To run the product: track your progress, schedule reviews, and personalize what you practice next.</Text>
          <Text>
            To generate practice content and feedback — quiz questions, roleplay replies, grammar
            corrections, and reading/listening passages are generated by an AI language model
            (via OpenRouter/DeepSeek) and by open dictionary and translation services.
          </Text>
          <Text>To send account emails you've asked for: email verification codes and password reset codes.</Text>
        </Section>

        <Section title="Where it's stored">
          <Text>
            Your data lives in a PostgreSQL database (hosted on Supabase, in the EU). It is not
            shared with data brokers or advertisers.
          </Text>
        </Section>

        <Section title="Third-party services we use">
          <Text>• OpenRouter/DeepSeek — generates AI practice content and tutoring feedback from text you send it.</Text>
          <Text>• Open dictionary and translation services (e.g. Wiktionary, Datamuse, a free dictionary API) — word definitions and translations.</Text>
          <Text>• Resend and Gmail SMTP — deliver verification and password-reset emails.</Text>
          <Text>None of these are used for advertising, and none receive your password.</Text>
        </Section>

        <Section title="Cookies & local storage">
          <Text>
            We use your browser's local storage to keep a sign-in token so you stay logged in —
            that's it. No third-party advertising or tracking cookies.
          </Text>
        </Section>

        <Section title="Your choices">
          <Text>
            You can update your profile and learning preferences at any time from your account
            menu in the app. To request a copy of your data or full account deletion, reach out
            through the app — we'll handle it directly.
          </Text>
        </Section>

        <Section title="Children">
          <Text>Vibeon Learn is not directed at children under 13, and we don't knowingly collect data from them.</Text>
        </Section>

        <Section title="Changes to this policy">
          <Text>
            If this policy changes in a way that matters, we'll update the date at the top of this
            page.
          </Text>
        </Section>
      </Stack>
    </Container>
  </Box>
);

export default PrivacyPolicyPage;
